service:
  LogTen:
    image: deretz/log_ten
    ports: 
      - "8080:8080"
    envs:
      - $TEN

  LogThree:
    image: deretz/log_three
    envs:
      - $THREE

networks:
  app-network:
    driver: bridge
