service:
  LogTen:
    image: deretz/log_ten
    envs:
      - $TEN
    replicas: 3

  LogFile:
    image: deretz/healthchecks
    ports:
      - "8000:8000"
    volume:
      - "/home/leo/code/LoadBalancer/log_input.txt:/app/log_input.txt"
    healthcheck:
      test:
        - "CMD"
        - "curl"
        - "--fail"
        - "http://localhost:8000/health"
      interval: 60
      timeout: 10
      retries: 3
      startperiod: 30
      startinterval: 2
