service:
  LogTen:
    image: deretz/log_ten
    network: 
      - app-network
    ports: 
      - "8080:8080"
    envs:
      - $TEN
    dependencies:
      - LogThree

  LogFive:
    image: deretz/log_five
    envs:
      - $FIVE

  LogThree:
    image: deretz/log_three
    dependencies:
      - LogFive
    envs:
      - $THREE

networks:
  app-network:
    driver: bridge
